[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[config]
indent = "\t"
line_length = 115

[hooks.yapf]
priority = 30

[hooks.isort]
priority = 50

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort.kwargs]
indent = "\t\t"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "coincidence",
    "coverage",
    "coverage_pyver_pragma",
    "dist_meta",
    "domdf_python_tools",
    "handy_archives",
    "hatchling",
    "importlib_metadata",
    "packaging",
    "pytest",
    "pytest_cov",
    "pytest_randomly",
    "pytest_timeout",
]
known_first_party = "hatch_requirements_txt"
